Add Edit Activity Page
sandboxnu/faculty-activity-tracker pull request #20
Opened 2023-04-05 04:45 UTC by Christinarlong

**Summary:**
- Added ability to edit activities by clicking on activity cards in submissions page
- Added Edit page route
- Modified FormInput to have an editing and non editing state
- Added ErrorBanner component (see image)
- Added last date modified label

**Images:**
<img width="661" alt="image" src="https://user-images.githubusercontent.com/60594860/229973462-de396e38-faa4-4a61-8dde-e000cea9fb66.png">
<img width="691" alt="image" src="https://user-images.githubusercontent.com/60594860/229983268-057d0fb4-e245-4781-9b25-b1d18f9fd9dd.png">

2023-04-05 16:07 UTC, maxpinheiro requested changes
Logic looks good, just a couple small changes. There are also conflicts with master, so please rebase your branch onto master, and then make the changes.

2023-04-05 16:07 UTC, maxpinheiro commented on src/components/ActivityForm/FormInput.tsx
> +        {isEditing ? (
we can do this with a single button, and put the `isEditing?` logic inside the `onClick`:

```
<button onClick={() => isEditing ? router.back() : dispatch(setStep('selection'))}>Back</button>
```

2023-04-06 17:13 UTC, maxpinheiro requested changes
Looks good, let's just clean up the duplicate files and then should be good to go

2023-04-06 17:13 UTC, maxpinheiro commented on src/components/Narratives/NarrativeInstructions 2.tsx
looks like a bunch of duplicate files got added during a rebase (`NarrativeInstructions 2.tsx`, `[...nextauth] 2.ts`, `profile.store 2.ts`, etc. the duplicates are identical to the original files, so let's just delete all the duplicates

2023-04-06 17:34 UTC, maxpinheiro approved these changes
Looks great! 🚢

2023-04-07 03:14 UTC, Christinarlong commented
> Looks great! 🚢

thanks sexy

2023-04-07 03:14 UTC, merged